@api = http://localhost:3000/recor

GET {{api}}

# aca busco la 1 por ejemplo 
GET {{api}}/1

GET {{api}}/count

POST {{api}}
Content-Type: application/json

{
    "ID_Usuario": "1",
    "Contrasena": "1234"
}